#!/usr/bin/env python
# coding: utf-8

# In[1]:


from bokeh.io import output_file, show, curdoc
from bokeh.plotting import figure
from bokeh.models import Div, Select, TextInput, BoxAnnotation, Toggle, ColumnDataSource, Label, LabelSet, Title
from bokeh.layouts import layout
from bokeh.resources import CDN
from bokeh.embed import file_html
from os.path import dirname, join
from bokeh.core.validation import silence
from bokeh.core.validation.warnings import EMPTY_LAYOUT
from bokeh.models.widgets import CheckboxGroup


# In[2]:


silence(EMPTY_LAYOUT, True)


# In[3]:


output_file("stacked.html", mode='inline')


# In[4]:


platform = ['Nintendo DS', 'Playstation 2', 'Playstation 3', 'Nintendo Wii', 'Xbox 360', 'Playstation Portable', 'Playstation 1', 'PC', 'Game Boy Advance', 'Xbox', 'GameCube', 'Nintendo 3DS', 'Playstation 4', 'Playstation Vita', 'Nintendo 64', 'Super Nintendo', 'Xbox One', 'Sega Saturn', 'Nintendo WiiU', 'Atari 2600', 'Nintendo Entertainment System', 'Game Boy', 'Sega Dreamcast', 'Sega Genesis']
genre = ['Sports', 'Racing', 'Platform', 'Puzzle', 'Simulation', 'Strategy', 'Misc', 'Shooter', 'Role-Playing', 'Action', 'Fighting', 'Adventure']
colors = ["#F4D611", "#C8B00E", "#BD3D3D", "#AF1313", "#901010", "#700D0D", "#500909", "#4a7cac", "#336596", "#295178", "#1f3d5a", "#15293c"]


# In[5]:


data = {'platform' : platform,
        'Sports'   : [148, 400, 213, 261, 220, 135, 222, 49, 88, 170, 110, 26, 43, 23, 80, 49, 36, 16, 8, 12, 14, 9, 10, 3],
        'Racing'   : [67, 216, 92, 94, 105, 65, 145, 60, 64, 123, 63, 11, 17, 11, 57, 9, 19, 8, 3, 6, 4, 2, 6, 1],
        'Platform' : [92, 103, 37, 58, 24, 36, 64, 11, 142, 49, 73, 28, 11, 10, 30, 26, 4, 5, 16, 9, 28, 19, 2, 7],
        'Puzzle' : [238, 18, 3, 55, 7, 44, 32, 25, 41, 7, 13, 20, 1, 3, 12, 13, 0, 5, 4, 11, 14, 15, 0, 0],
        'Simulation' : [285, 90, 31, 87, 40, 29, 60, 115, 18, 24, 12, 30, 5, 3, 10, 9, 3, 7, 1, 1, 0, 5, 1, 0],
        'Strategy'   : [79, 71, 24, 25, 28, 60, 70, 188, 18, 21, 11, 15, 5, 7, 9, 15, 3, 18, 3, 0, 0, 7, 0, 1],
        'Misc'   : [393, 222, 124, 280, 126, 106, 76, 24, 110, 46, 36, 53, 15, 24, 18, 17, 15, 15, 21, 5, 2, 8, 0, 1],
        'Shooter'   : [42, 160, 156, 66, 203, 37, 96, 148, 40, 132, 48, 7, 34, 5, 24, 10, 33, 22, 10, 24, 7, 1, 3, 1],
        'Role-Playing'   : [200, 187, 119, 35, 76, 192, 97, 104, 73, 23, 27, 86, 47, 83, 8, 50, 13, 17, 6, 0, 11, 21, 4, 3],
        'Action'   : [343, 348, 380, 238, 324, 222, 157, 165, 167, 145, 101, 182, 122, 142, 38, 12, 68, 3, 63, 61, 13, 6, 3, 3],
        'Fighting'   : [36, 150, 76, 42, 65, 74, 108, 6, 23, 48, 42, 14, 17, 16, 29, 25, 7, 31, 5, 2, 4, 0, 12, 5],
        'Adventure' : [240, 196, 74, 84, 47, 213, 69, 65, 38, 26, 20, 37, 122, 86, 38, 4, 12, 26, 3, 2, 1, 5, 11, 2]}


# In[6]:


TOOLTIPS = """
<div style="padding: 6pt; border-left-style: solid;">
    <div>
        <span style="font-size: 12px; font-weight: bold;">$name: @$name</span>
    </div>
    <div>
        <span style="font-size: 11.5px; font-style: italic;">@platform</span>
    </div>
"""


# In[7]:


p = figure(x_range=platform, plot_height=800, plot_width=1000, title="Video Game Releases by Platform and Genre",
           toolbar_location=None, tools="hover", tooltips=TOOLTIPS)


# In[8]:


source = ColumnDataSource(data=data)


# In[9]:


p.vbar_stack(genre, x='platform', width=0.9, color=colors, source=source,
            legend_label=genre)


# In[10]:


p.yaxis.axis_label = 'Total Number of Releases'
p.xaxis.axis_label = 'Platform'


# In[11]:


p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_right"
p.legend.orientation = "vertical"
p.xaxis.major_label_orientation = "vertical"


# In[12]:


labels = LabelSet(x='x', y='y', text='y', level='glyph',
        source=source, render_mode='canvas')


# In[13]:


p.title.text_font_size = "20pt"


# In[14]:


p.add_layout(Title(text="This dataset contains a list of video games with sales greater than 100,000 copies up to October 2016. It was generated by a scrape of vgchartz.com.", text_font_style="italic"), 'above')


# In[15]:


p.legend.click_policy="hide"
p.legend.title = 'Genres (click to hide)'


# In[16]:


show(p)


# In[ ]:




